### ISSUE TITLE
on error, should flush stdout

### ISSUE THREAD

**Issue by timotheecour** [AndreiRegiani/INim#30]
in both cases of https://github.com/AndreiRegiani/INim/issues/29, there's a flush missing:
the result of 1st echo isn't shown

whereas `nim` itself does flush:
```
nim c -o:app -r bugs/t59_array_index.nim
...
@["a", "b", "c"] # <= HERE
/Users/timothee/git_clone/nim/timn/bugs/t59_array_index.nim(3) t59_array_index
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3597) []
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2807) sysFatal
Error: unhandled exception: index out of bounds [IndexError]
Error: execution of an external program failed: './app '
```

**Comment by AndreiRegiani** [comment]
Should be fixed now, can you verify?

**Comment by timotheecour** [comment]
`@["a", "b", "c"]` still not shown in inim 0.4.1

inim -s=bugs/t59_array_index.nim
👑 INim 0.4.1
Nim Compiler Version 0.18.1 [MacOSX: amd64] at /Users/timothee/.nimble//bin/nim
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3597) []
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2807) sysFatal
Error: unhandled exception: index out of bounds [IndexError]

nim c -o:app -r bugs/t59_array_index.nim
Hint: operation successful (12266 lines compiled; 0.382 sec total; 16.289MiB peakmem; Debug Build) [SuccessX]
@["a", "b", "c"]
/Users/timothee/git_clone/nim/timn/bugs/t59_array_index.nim(4) t59_array_index
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3597) []
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2807) sysFatal
Error: unhandled exception: index out of bounds [IndexError]
Error: execution of an external program failed: './app '
